# Generated by Django 5.1.2 on 2024-10-23 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_check_in_time_alter_room_check_out_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="room_image",
            name="is_representative",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="check_in_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="check_out_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room_image",
            name="image",
            field=models.ImageField(upload_to="room_images"),
        ),
        migrations.AddConstraint(
            model_name="room_image",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_representative", True)),
                fields=("room", "is_representative"),
                name="unique_representative_image_per_room",
            ),
        ),
    ]
