# Generated by Django 5.1.2 on 2024-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_image_is_representative_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="check_in_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="check_out_time",
            field=models.TimeField(),
        ),
    ]
