# Generated by Django 5.1.2 on 2024-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("guest", "Guest"), ("host", "Host"), ("admin", "Administrator")],
                default="guest",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawmanager",
            name="withdraw_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
