# Generated by Django 5.1.2 on 2024-10-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accommodations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.businessuser"
            ),
        ),
        migrations.AddField(
            model_name="accommodation_image",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="accommodationtype",
            name="accommodation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="gps_info",
            name="accommodation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.accommodation",
            ),
        ),
    ]
