# Generated by Django 5.1.2 on 2024-10-21 08:32

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gps_info",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="gps_info",
            name="longitude",
        ),
        migrations.AddField(
            model_name="gps_info",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326
            ),
        ),
    ]
