# Generated by Django 5.1.2 on 2024-10-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0003_remove_gps_info_latitude_remove_gps_info_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seven_days_before", models.DecimalField(decimal_places=2, max_digits=5)),
                ("five_days_before", models.DecimalField(decimal_places=2, max_digits=5)),
                ("three_days_before", models.DecimalField(decimal_places=2, max_digits=5)),
                ("one_day_before", models.DecimalField(decimal_places=2, max_digits=5)),
                ("same_day", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="accommodation_image",
            name="is_representative",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accommodation_image",
            name="image",
            field=models.ImageField(upload_to="accommodation_images"),
        ),
        migrations.AddConstraint(
            model_name="accommodation_image",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_representative", True)),
                fields=("accommodation", "is_representative"),
                name="unique_representative_image_per_accommodation",
            ),
        ),
        migrations.AddField(
            model_name="refundpolicy",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund_policies",
                to="accommodations.accommodation",
            ),
        ),
    ]
