# Generated by Django 5.1.2 on 2024-10-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.PositiveIntegerField(),
        ),
    ]
