# Generated by Django 5.1.2 on 2024-10-24 07:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_booker_name_booking_booker_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="check_in_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="check_out_date",
        ),
        migrations.AddField(
            model_name="booking",
            name="check_in_datetime",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_datetime",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
