"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6)2#$$liu%$bzu8-%q-87hk#_#m=ycw2^)1ekjs*z9tv$*p*@k"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv("DEBUG", "True")
DEBUG = True

ALLOWED_HOSTS = ["52.78.188.221", "localhost", "127.0.0.1"]

load_dotenv(os.path.join(BASE_DIR, ".env"))

# postgresql gdal settings

GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH", "/usr/lib/aarch64-linux-gnu/libgdal.so")
GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH", "/usr/lib/aarch64-linux-gnu/libgeos_c.so")


# Application definition

OWN_APPS = [
    "apps.users",
    "apps.rooms",
    "apps.accommodations",
    "apps.bookings",
    "apps.reviews",
    "apps.amenities",
    "apps.bookmarks",
    "apps.common",
]

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
]

THIRD_PARTY_APPS = [
    "corsheaders",
    "channels",  # Django Channels
    "django_apscheduler",  # APScheduler
    "rest_framework",  # Django Rest Framework
    "rest_framework_gis",
    "rest_framework_simplejwt",  # DRF Simple JWT
    "rest_framework_simplejwt.token_blacklist",  # DRF Simple JWT BlackList
    "drf_spectacular",  # DRF Spectacular (API 문서화)
    "django_filters",  # Django Filter for DRF
]

INSTALLED_APPS = OWN_APPS + DJANGO_APPS + THIRD_PARTY_APPS


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "https://localhost:3000",
    "https://localhost:5173",
    "http://localhost:8000",
    "https://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "https://127.0.0.1:3000",
    "https://127.0.0.1:5173",
    "http://127.0.0.1:8000",
    "https://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

if DEBUG and "test" not in sys.argv:  # 테스트 환경에서 비활성화
    import socket  # only if you haven't already imported this

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + [
        "127.0.0.1",
        "52.78.188.221",
    ]
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,  # 모든 요청에서 툴바를 보이도록 설정
    }
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INSTALLED_APPS += ["debug_toolbar"]

else:
    # 테스트 환경에서 Debug Toolbar 비활성화
    if "debug_toolbar" in INSTALLED_APPS:
        INSTALLED_APPS.remove("debug_toolbar")
    MIDDLEWARE = [mw for mw in MIDDLEWARE if mw != "debug_toolbar.middleware.DebugToolbarMiddleware"]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.postgresql_psycopg2",
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("DB_NAME", "oz_main"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# settings.py

AUTH_USER_MODEL = "users.User"

# email settings

# 이메일 백엔드 설정
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# SMTP 서버 설정 (예: Gmail 사용)
EMAIL_HOST = "smtp.naver.com"  # SMTP 서버 주소
EMAIL_PORT = 587  # 포트 번호 (Gmail은 587)
EMAIL_USE_TLS = True  # TLS 사용 여부 (Gmail은 True)

# 이메일 인증 정보
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "your_email@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "your_email_password")

# 기본 발신자 이메일 주소
DEFAULT_FROM_EMAIL = "webmaster@yourdomain.com"  # 발신자 기본 이메일

# 세션 설정 (선택 사항)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# drf settings

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "EXCEPTION_HANDLER": "apps.common.util.custom_exception_handler.validation_error_handler.custom_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "My API",
    "DESCRIPTION": "API documentation for my project",
    "VERSION": "1.0.0",
    "TAGS": [
        {"name": "User", "description": "User API"},
        {"name": "Guest", "description": "Guest API"},
        {"name": "Host", "description": "Host API"},
    ],
    "COMPONENT_SPLIT_REQUEST": True,
}


# jwt settings

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=240),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": os.getenv("JWT_SECRET_KEY", "default-secret-key"),
}

# kakao_rest_api_key

KAKAO_REST_API_KEY = os.getenv("KAKAO_REST_API_KEY", "your-kakao-rest-api-key")

# naver_rest_api_key

NAVER_REST_API_KEY = os.getenv("NAVER_CLIENT_ID", "your-naver-rest-api-key")
NAVER_REST_API_SECRET = os.getenv("NAVER_SECRET_ID", "your-naver-rest-api-secret")

# 최대 업로드 크기 설정
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
# if DEBUG:
#     SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"] = timedelta(days=3650)  # 개발 환경용 긴 토큰
# else:
#     SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"] = timedelta(minutes=5)  # 실제 배포 환경용 짧은 토큰


# Aws S3 settings

if not DEBUG:
    # 프로덕션 환경 - S3 + CloudFront 설정
    INSTALLED_APPS += ["storages"]

    # CloudFront 도메인 이름 설정
    CLOUDFRONT_DOMAIN = os.getenv("CLOUDFRONT_DOMAIN")  # 예: 'd1234abcd.cloudfront.net'

    # STORAGES 설정
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
                "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
                "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
                "region_name": os.getenv("AWS_S3_REGION_NAME"),
                "location": "media",
                "default_acl": None,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
                "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
                "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
                "region_name": os.getenv("AWS_S3_REGION_NAME"),
                "custom_domain": CLOUDFRONT_DOMAIN,  # CloudFront 도메인 사용
                "location": "static",
                "default_acl": None,
            },
        },
    }

    # CloudFront를 사용한 URL 설정
    MEDIA_URL = f"https://{CLOUDFRONT_DOMAIN}/backend/media/"
    STATIC_URL = f"https://{CLOUDFRONT_DOMAIN}/backend/static/"

    # 쿼리 인증 매개변수를 URL에 포함하지 않음
    AWS_QUERYSTRING_AUTH = False

    # STATIC_ROOT 경로 설정 (임시 파일 시스템 경로)
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # 로컬 파일 시스템 경로 지정

else:
    # 개발 환경 - 로컬 파일 시스템 설정
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
# # 캐시 설정 (선택 사항)
# AWS_QUERYSTRING_AUTH = False  # S3 링크에 인증 매개변수를 포함하지 않음
