# Generated by Django 5.1.2 on 2024-10-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accommodations", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("is_custom", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("is_custom", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AccommodationAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accommodations.accommodation",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amenities.amenity",
                    ),
                ),
            ],
            options={
                "unique_together": {("accommodation", "amenity")},
            },
        ),
        migrations.CreateModel(
            name="RoomOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amenities.option",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rooms.room"),
                ),
            ],
            options={
                "unique_together": {("room", "option")},
            },
        ),
    ]
