# Generated by Django 5.1.2 on 2024-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodationamenity",
            name="custom_value",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="roomoption",
            name="custom_value",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
